// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package tcpedge

import (
	context "context"

	core "github.com/ksysoev/make-it-public/pkg/core"
	mock "github.com/stretchr/testify/mock"

	net "net"
)

// MockConnService is an autogenerated mock type for the ConnService type
type MockConnService struct {
	mock.Mock
}

type MockConnService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnService) EXPECT() *MockConnService_Expecter {
	return &MockConnService_Expecter{mock: &_m.Mock}
}

// HandleTCPConnection provides a mock function with given fields: ctx, keyID, conn, clientIP
func (_m *MockConnService) HandleTCPConnection(ctx context.Context, keyID string, conn net.Conn, clientIP string) error {
	ret := _m.Called(ctx, keyID, conn, clientIP)

	if len(ret) == 0 {
		panic("no return value specified for HandleTCPConnection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, net.Conn, string) error); ok {
		r0 = rf(ctx, keyID, conn, clientIP)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConnService_HandleTCPConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleTCPConnection'
type MockConnService_HandleTCPConnection_Call struct {
	*mock.Call
}

// HandleTCPConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID string
//   - conn net.Conn
//   - clientIP string
func (_e *MockConnService_Expecter) HandleTCPConnection(ctx interface{}, keyID interface{}, conn interface{}, clientIP interface{}) *MockConnService_HandleTCPConnection_Call {
	return &MockConnService_HandleTCPConnection_Call{Call: _e.mock.On("HandleTCPConnection", ctx, keyID, conn, clientIP)}
}

func (_c *MockConnService_HandleTCPConnection_Call) Run(run func(ctx context.Context, keyID string, conn net.Conn, clientIP string)) *MockConnService_HandleTCPConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(net.Conn), args[3].(string))
	})
	return _c
}

func (_c *MockConnService_HandleTCPConnection_Call) Return(_a0 error) *MockConnService_HandleTCPConnection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnService_HandleTCPConnection_Call) RunAndReturn(run func(context.Context, string, net.Conn, string) error) *MockConnService_HandleTCPConnection_Call {
	_c.Call.Return(run)
	return _c
}

// SetTCPEndpointAllocator provides a mock function with given fields: allocator
func (_m *MockConnService) SetTCPEndpointAllocator(allocator core.TCPEndpointAllocator) {
	_m.Called(allocator)
}

// MockConnService_SetTCPEndpointAllocator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTCPEndpointAllocator'
type MockConnService_SetTCPEndpointAllocator_Call struct {
	*mock.Call
}

// SetTCPEndpointAllocator is a helper method to define mock.On call
//   - allocator core.TCPEndpointAllocator
func (_e *MockConnService_Expecter) SetTCPEndpointAllocator(allocator interface{}) *MockConnService_SetTCPEndpointAllocator_Call {
	return &MockConnService_SetTCPEndpointAllocator_Call{Call: _e.mock.On("SetTCPEndpointAllocator", allocator)}
}

func (_c *MockConnService_SetTCPEndpointAllocator_Call) Run(run func(allocator core.TCPEndpointAllocator)) *MockConnService_SetTCPEndpointAllocator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(core.TCPEndpointAllocator))
	})
	return _c
}

func (_c *MockConnService_SetTCPEndpointAllocator_Call) Return() *MockConnService_SetTCPEndpointAllocator_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnService_SetTCPEndpointAllocator_Call) RunAndReturn(run func(core.TCPEndpointAllocator)) *MockConnService_SetTCPEndpointAllocator_Call {
	_c.Run(run)
	return _c
}

// NewMockConnService creates a new instance of MockConnService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnService {
	mock := &MockConnService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
