services:
  redis:
    image: docker.io/bitnami/redis:7.4.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379"
  
  mitserver:
    image: "ghcr.io/ksysoev/make-it-public:main"
    restart: unless-stopped
    container_name: mitserver
    ports:
      - "8080:8080" # HTTP server
      - "8081:8081" # Reverse proxy
      - "8082:8082" # API server
    volumes:
      - ./runtime/config.yaml:/runtime/config.yaml
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mitserver
