services:
  redis:
    image: docker.io/bitnami/redis:7.4.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379"

  mitserver:
    # comment this for local build
    # image: "ghcr.io/ksysoev/make-it-public:main"
    # uncomment this for local build
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: mitserver
    ports:
      - "8080" # HTTP server
      - "8081:8081" # Reverse proxy
      - "8082:8082" # API server
    volumes:
      - ./runtime/config.yaml:/runtime/config.yaml
      - ./docs/swagger.json:/docs/swagger.json
    depends_on:
      - redis


  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:2.10-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - EMAIL=${EMAIL}
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - ./conf:/etc/caddy
      - ./static:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - mitserver

volumes:
  caddy_data:
  caddy_config:
