services:
  redis:
    image: docker.io/bitnami/redis:7.4.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379"

  mitserver:
    build:
      context: .
      dockerfile: Dockerfile
    # image: "ghcr.io/ksysoev/make-it-public:main"
    restart: unless-stopped
    container_name: mitserver
    ports:
      - "8080" # HTTP server
      - "8081:8081" # Reverse proxy
      - "8082:8082" # API server
      - "9009:9009" # Metrics server
    environment:
      - AUTH_REDIS_ADDR=redis:6379
      - AUTH_SALT=${AUTH_SALT}
      - HTTP_PUBLIC_SCHEMA=https
      - HTTP_PUBLIC_DOMAIN=test
      - HTTP_LISTEN=:8080
      - REVERSE_PROXY_LISTEN=:8081
      - METRICS_LISTEN=:9009
      - API_LISTEN=:8082
      - API_DEFAULT_TOKEN_EXPIRY=3600
      - LOG_LEVEL=info
      - LOG_TEXT=false
    command: ["server", "run", "all" ]
    depends_on:
      - redis


  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:2.10-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - EMAIL=${EMAIL}
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - ./runtime/Caddyfile:/etc/caddy/Caddyfile
      - ./static:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - mitserver

volumes:
  caddy_data:
  caddy_config:
