// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package api

import (
	context "context"

	token "github.com/ksysoev/make-it-public/pkg/core/token"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// DeleteToken provides a mock function with given fields: ctx, tokenID
func (_m *MockService) DeleteToken(ctx context.Context, tokenID string) error {
	ret := _m.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteToken'
type MockService_DeleteToken_Call struct {
	*mock.Call
}

// DeleteToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *MockService_Expecter) DeleteToken(ctx interface{}, tokenID interface{}) *MockService_DeleteToken_Call {
	return &MockService_DeleteToken_Call{Call: _e.mock.On("DeleteToken", ctx, tokenID)}
}

func (_c *MockService_DeleteToken_Call) Run(run func(ctx context.Context, tokenID string)) *MockService_DeleteToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_DeleteToken_Call) Return(_a0 error) *MockService_DeleteToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteToken_Call) RunAndReturn(run func(context.Context, string) error) *MockService_DeleteToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateToken provides a mock function with given fields: ctx, keyID, ttl
func (_m *MockService) GenerateToken(ctx context.Context, keyID string, ttl int) (*token.Token, error) {
	ret := _m.Called(ctx, keyID, ttl)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 *token.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (*token.Token, error)); ok {
		return rf(ctx, keyID, ttl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *token.Token); ok {
		r0 = rf(ctx, keyID, ttl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, keyID, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GenerateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateToken'
type MockService_GenerateToken_Call struct {
	*mock.Call
}

// GenerateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID string
//   - ttl int
func (_e *MockService_Expecter) GenerateToken(ctx interface{}, keyID interface{}, ttl interface{}) *MockService_GenerateToken_Call {
	return &MockService_GenerateToken_Call{Call: _e.mock.On("GenerateToken", ctx, keyID, ttl)}
}

func (_c *MockService_GenerateToken_Call) Run(run func(ctx context.Context, keyID string, ttl int)) *MockService_GenerateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockService_GenerateToken_Call) Return(_a0 *token.Token, _a1 error) *MockService_GenerateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GenerateToken_Call) RunAndReturn(run func(context.Context, string, int) (*token.Token, error)) *MockService_GenerateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
