// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package conn

import (
	context "context"
	net "net"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockConnReq is an autogenerated mock type for the Req type
type MockConnReq struct {
	mock.Mock
}

type MockConnReq_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnReq) EXPECT() *MockConnReq_Expecter {
	return &MockConnReq_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with no fields
func (_m *MockConnReq) Cancel() {
	_m.Called()
}

// MockConnReq_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockConnReq_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
func (_e *MockConnReq_Expecter) Cancel() *MockConnReq_Cancel_Call {
	return &MockConnReq_Cancel_Call{Call: _e.mock.On("Cancel")}
}

func (_c *MockConnReq_Cancel_Call) Run(run func()) *MockConnReq_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnReq_Cancel_Call) Return() *MockConnReq_Cancel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnReq_Cancel_Call) RunAndReturn(run func()) *MockConnReq_Cancel_Call {
	_c.Run(run)
	return _c
}

// ID provides a mock function with no fields
func (_m *MockConnReq) ID() uuid.UUID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	return r0
}

// MockConnReq_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockConnReq_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockConnReq_Expecter) ID() *MockConnReq_ID_Call {
	return &MockConnReq_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockConnReq_ID_Call) Run(run func()) *MockConnReq_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnReq_ID_Call) Return(_a0 uuid.UUID) *MockConnReq_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnReq_ID_Call) RunAndReturn(run func() uuid.UUID) *MockConnReq_ID_Call {
	_c.Call.Return(run)
	return _c
}

// ParentContext provides a mock function with no fields
func (_m *MockConnReq) ParentContext() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ParentContext")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// MockConnReq_ParentContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParentContext'
type MockConnReq_ParentContext_Call struct {
	*mock.Call
}

// ParentContext is a helper method to define mock.On call
func (_e *MockConnReq_Expecter) ParentContext() *MockConnReq_ParentContext_Call {
	return &MockConnReq_ParentContext_Call{Call: _e.mock.On("ParentContext")}
}

func (_c *MockConnReq_ParentContext_Call) Run(run func()) *MockConnReq_ParentContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnReq_ParentContext_Call) Return(_a0 context.Context) *MockConnReq_ParentContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnReq_ParentContext_Call) RunAndReturn(run func() context.Context) *MockConnReq_ParentContext_Call {
	_c.Call.Return(run)
	return _c
}

// SendConn provides a mock function with given fields: ctx, _a1
func (_m *MockConnReq) SendConn(ctx context.Context, _a1 net.Conn) {
	_m.Called(ctx, _a1)
}

// MockConnReq_SendConn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendConn'
type MockConnReq_SendConn_Call struct {
	*mock.Call
}

// SendConn is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 net.Conn
func (_e *MockConnReq_Expecter) SendConn(ctx interface{}, _a1 interface{}) *MockConnReq_SendConn_Call {
	return &MockConnReq_SendConn_Call{Call: _e.mock.On("SendConn", ctx, _a1)}
}

func (_c *MockConnReq_SendConn_Call) Run(run func(ctx context.Context, _a1 net.Conn)) *MockConnReq_SendConn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(net.Conn))
	})
	return _c
}

func (_c *MockConnReq_SendConn_Call) Return() *MockConnReq_SendConn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnReq_SendConn_Call) RunAndReturn(run func(context.Context, net.Conn)) *MockConnReq_SendConn_Call {
	_c.Run(run)
	return _c
}

// WaitConn provides a mock function with given fields: ctx
func (_m *MockConnReq) WaitConn(ctx context.Context) (net.Conn, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for WaitConn")
	}

	var r0 net.Conn
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (net.Conn, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) net.Conn); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnReq_WaitConn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitConn'
type MockConnReq_WaitConn_Call struct {
	*mock.Call
}

// WaitConn is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConnReq_Expecter) WaitConn(ctx interface{}) *MockConnReq_WaitConn_Call {
	return &MockConnReq_WaitConn_Call{Call: _e.mock.On("WaitConn", ctx)}
}

func (_c *MockConnReq_WaitConn_Call) Run(run func(ctx context.Context)) *MockConnReq_WaitConn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockConnReq_WaitConn_Call) Return(_a0 net.Conn, _a1 error) *MockConnReq_WaitConn_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnReq_WaitConn_Call) RunAndReturn(run func(context.Context) (net.Conn, error)) *MockConnReq_WaitConn_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConnReq creates a new instance of MockConnReq. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnReq(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnReq {
	mock := &MockConnReq{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
