// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package conn

import (
	net "net"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockWithWriteCloser is an autogenerated mock type for the WithWriteCloser type
type MockWithWriteCloser struct {
	mock.Mock
}

type MockWithWriteCloser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWithWriteCloser) EXPECT() *MockWithWriteCloser_Expecter {
	return &MockWithWriteCloser_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockWithWriteCloser) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWithWriteCloser_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockWithWriteCloser_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockWithWriteCloser_Expecter) Close() *MockWithWriteCloser_Close_Call {
	return &MockWithWriteCloser_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockWithWriteCloser_Close_Call) Run(run func()) *MockWithWriteCloser_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWithWriteCloser_Close_Call) Return(_a0 error) *MockWithWriteCloser_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWithWriteCloser_Close_Call) RunAndReturn(run func() error) *MockWithWriteCloser_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CloseWrite provides a mock function with no fields
func (_m *MockWithWriteCloser) CloseWrite() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseWrite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWithWriteCloser_CloseWrite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseWrite'
type MockWithWriteCloser_CloseWrite_Call struct {
	*mock.Call
}

// CloseWrite is a helper method to define mock.On call
func (_e *MockWithWriteCloser_Expecter) CloseWrite() *MockWithWriteCloser_CloseWrite_Call {
	return &MockWithWriteCloser_CloseWrite_Call{Call: _e.mock.On("CloseWrite")}
}

func (_c *MockWithWriteCloser_CloseWrite_Call) Run(run func()) *MockWithWriteCloser_CloseWrite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWithWriteCloser_CloseWrite_Call) Return(_a0 error) *MockWithWriteCloser_CloseWrite_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWithWriteCloser_CloseWrite_Call) RunAndReturn(run func() error) *MockWithWriteCloser_CloseWrite_Call {
	_c.Call.Return(run)
	return _c
}

// LocalAddr provides a mock function with no fields
func (_m *MockWithWriteCloser) LocalAddr() net.Addr {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LocalAddr")
	}

	var r0 net.Addr
	if rf, ok := ret.Get(0).(func() net.Addr); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Addr)
		}
	}

	return r0
}

// MockWithWriteCloser_LocalAddr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LocalAddr'
type MockWithWriteCloser_LocalAddr_Call struct {
	*mock.Call
}

// LocalAddr is a helper method to define mock.On call
func (_e *MockWithWriteCloser_Expecter) LocalAddr() *MockWithWriteCloser_LocalAddr_Call {
	return &MockWithWriteCloser_LocalAddr_Call{Call: _e.mock.On("LocalAddr")}
}

func (_c *MockWithWriteCloser_LocalAddr_Call) Run(run func()) *MockWithWriteCloser_LocalAddr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWithWriteCloser_LocalAddr_Call) Return(_a0 net.Addr) *MockWithWriteCloser_LocalAddr_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWithWriteCloser_LocalAddr_Call) RunAndReturn(run func() net.Addr) *MockWithWriteCloser_LocalAddr_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: b
func (_m *MockWithWriteCloser) Read(b []byte) (int, error) {
	ret := _m.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(b)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(b)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(b)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWithWriteCloser_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockWithWriteCloser_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - b []byte
func (_e *MockWithWriteCloser_Expecter) Read(b interface{}) *MockWithWriteCloser_Read_Call {
	return &MockWithWriteCloser_Read_Call{Call: _e.mock.On("Read", b)}
}

func (_c *MockWithWriteCloser_Read_Call) Run(run func(b []byte)) *MockWithWriteCloser_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockWithWriteCloser_Read_Call) Return(n int, err error) *MockWithWriteCloser_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockWithWriteCloser_Read_Call) RunAndReturn(run func([]byte) (int, error)) *MockWithWriteCloser_Read_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteAddr provides a mock function with no fields
func (_m *MockWithWriteCloser) RemoteAddr() net.Addr {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemoteAddr")
	}

	var r0 net.Addr
	if rf, ok := ret.Get(0).(func() net.Addr); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Addr)
		}
	}

	return r0
}

// MockWithWriteCloser_RemoteAddr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteAddr'
type MockWithWriteCloser_RemoteAddr_Call struct {
	*mock.Call
}

// RemoteAddr is a helper method to define mock.On call
func (_e *MockWithWriteCloser_Expecter) RemoteAddr() *MockWithWriteCloser_RemoteAddr_Call {
	return &MockWithWriteCloser_RemoteAddr_Call{Call: _e.mock.On("RemoteAddr")}
}

func (_c *MockWithWriteCloser_RemoteAddr_Call) Run(run func()) *MockWithWriteCloser_RemoteAddr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWithWriteCloser_RemoteAddr_Call) Return(_a0 net.Addr) *MockWithWriteCloser_RemoteAddr_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWithWriteCloser_RemoteAddr_Call) RunAndReturn(run func() net.Addr) *MockWithWriteCloser_RemoteAddr_Call {
	_c.Call.Return(run)
	return _c
}

// SetDeadline provides a mock function with given fields: t
func (_m *MockWithWriteCloser) SetDeadline(t time.Time) error {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for SetDeadline")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWithWriteCloser_SetDeadline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDeadline'
type MockWithWriteCloser_SetDeadline_Call struct {
	*mock.Call
}

// SetDeadline is a helper method to define mock.On call
//   - t time.Time
func (_e *MockWithWriteCloser_Expecter) SetDeadline(t interface{}) *MockWithWriteCloser_SetDeadline_Call {
	return &MockWithWriteCloser_SetDeadline_Call{Call: _e.mock.On("SetDeadline", t)}
}

func (_c *MockWithWriteCloser_SetDeadline_Call) Run(run func(t time.Time)) *MockWithWriteCloser_SetDeadline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time))
	})
	return _c
}

func (_c *MockWithWriteCloser_SetDeadline_Call) Return(_a0 error) *MockWithWriteCloser_SetDeadline_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWithWriteCloser_SetDeadline_Call) RunAndReturn(run func(time.Time) error) *MockWithWriteCloser_SetDeadline_Call {
	_c.Call.Return(run)
	return _c
}

// SetReadDeadline provides a mock function with given fields: t
func (_m *MockWithWriteCloser) SetReadDeadline(t time.Time) error {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for SetReadDeadline")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWithWriteCloser_SetReadDeadline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetReadDeadline'
type MockWithWriteCloser_SetReadDeadline_Call struct {
	*mock.Call
}

// SetReadDeadline is a helper method to define mock.On call
//   - t time.Time
func (_e *MockWithWriteCloser_Expecter) SetReadDeadline(t interface{}) *MockWithWriteCloser_SetReadDeadline_Call {
	return &MockWithWriteCloser_SetReadDeadline_Call{Call: _e.mock.On("SetReadDeadline", t)}
}

func (_c *MockWithWriteCloser_SetReadDeadline_Call) Run(run func(t time.Time)) *MockWithWriteCloser_SetReadDeadline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time))
	})
	return _c
}

func (_c *MockWithWriteCloser_SetReadDeadline_Call) Return(_a0 error) *MockWithWriteCloser_SetReadDeadline_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWithWriteCloser_SetReadDeadline_Call) RunAndReturn(run func(time.Time) error) *MockWithWriteCloser_SetReadDeadline_Call {
	_c.Call.Return(run)
	return _c
}

// SetWriteDeadline provides a mock function with given fields: t
func (_m *MockWithWriteCloser) SetWriteDeadline(t time.Time) error {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for SetWriteDeadline")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWithWriteCloser_SetWriteDeadline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWriteDeadline'
type MockWithWriteCloser_SetWriteDeadline_Call struct {
	*mock.Call
}

// SetWriteDeadline is a helper method to define mock.On call
//   - t time.Time
func (_e *MockWithWriteCloser_Expecter) SetWriteDeadline(t interface{}) *MockWithWriteCloser_SetWriteDeadline_Call {
	return &MockWithWriteCloser_SetWriteDeadline_Call{Call: _e.mock.On("SetWriteDeadline", t)}
}

func (_c *MockWithWriteCloser_SetWriteDeadline_Call) Run(run func(t time.Time)) *MockWithWriteCloser_SetWriteDeadline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time))
	})
	return _c
}

func (_c *MockWithWriteCloser_SetWriteDeadline_Call) Return(_a0 error) *MockWithWriteCloser_SetWriteDeadline_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWithWriteCloser_SetWriteDeadline_Call) RunAndReturn(run func(time.Time) error) *MockWithWriteCloser_SetWriteDeadline_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: b
func (_m *MockWithWriteCloser) Write(b []byte) (int, error) {
	ret := _m.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(b)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(b)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(b)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWithWriteCloser_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockWithWriteCloser_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - b []byte
func (_e *MockWithWriteCloser_Expecter) Write(b interface{}) *MockWithWriteCloser_Write_Call {
	return &MockWithWriteCloser_Write_Call{Call: _e.mock.On("Write", b)}
}

func (_c *MockWithWriteCloser_Write_Call) Run(run func(b []byte)) *MockWithWriteCloser_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockWithWriteCloser_Write_Call) Return(n int, err error) *MockWithWriteCloser_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockWithWriteCloser_Write_Call) RunAndReturn(run func([]byte) (int, error)) *MockWithWriteCloser_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWithWriteCloser creates a new instance of MockWithWriteCloser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWithWriteCloser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWithWriteCloser {
	mock := &MockWithWriteCloser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
