// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package edge

import (
	context "context"
	net "net"

	mock "github.com/stretchr/testify/mock"
)

// MockConnService is an autogenerated mock type for the ConnService type
type MockConnService struct {
	mock.Mock
}

type MockConnService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnService) EXPECT() *MockConnService_Expecter {
	return &MockConnService_Expecter{mock: &_m.Mock}
}

// HandleHTTPConnection provides a mock function with given fields: ctx, userID, conn, write
func (_m *MockConnService) HandleHTTPConnection(ctx context.Context, userID string, conn net.Conn, write func(net.Conn) error) error {
	ret := _m.Called(ctx, userID, conn, write)

	if len(ret) == 0 {
		panic("no return value specified for HandleHTTPConnection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, net.Conn, func(net.Conn) error) error); ok {
		r0 = rf(ctx, userID, conn, write)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConnService_HandleHTTPConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleHTTPConnection'
type MockConnService_HandleHTTPConnection_Call struct {
	*mock.Call
}

// HandleHTTPConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - conn net.Conn
//   - write func(net.Conn) error
func (_e *MockConnService_Expecter) HandleHTTPConnection(ctx interface{}, userID interface{}, conn interface{}, write interface{}) *MockConnService_HandleHTTPConnection_Call {
	return &MockConnService_HandleHTTPConnection_Call{Call: _e.mock.On("HandleHTTPConnection", ctx, userID, conn, write)}
}

func (_c *MockConnService_HandleHTTPConnection_Call) Run(run func(ctx context.Context, userID string, conn net.Conn, write func(net.Conn) error)) *MockConnService_HandleHTTPConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(net.Conn), args[3].(func(net.Conn) error))
	})
	return _c
}

func (_c *MockConnService_HandleHTTPConnection_Call) Return(_a0 error) *MockConnService_HandleHTTPConnection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnService_HandleHTTPConnection_Call) RunAndReturn(run func(context.Context, string, net.Conn, func(net.Conn) error) error) *MockConnService_HandleHTTPConnection_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConnService creates a new instance of MockConnService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnService {
	mock := &MockConnService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
