// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package core

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthRepo is an autogenerated mock type for the AuthRepo type
type MockAuthRepo struct {
	mock.Mock
}

type MockAuthRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthRepo) EXPECT() *MockAuthRepo_Expecter {
	return &MockAuthRepo_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function with given fields: ctx, keyID, secret
func (_m *MockAuthRepo) Verify(ctx context.Context, keyID string, secret string) (bool, error) {
	ret := _m.Called(ctx, keyID, secret)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, keyID, secret)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, keyID, secret)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, keyID, secret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthRepo_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockAuthRepo_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID string
//   - secret string
func (_e *MockAuthRepo_Expecter) Verify(ctx interface{}, keyID interface{}, secret interface{}) *MockAuthRepo_Verify_Call {
	return &MockAuthRepo_Verify_Call{Call: _e.mock.On("Verify", ctx, keyID, secret)}
}

func (_c *MockAuthRepo_Verify_Call) Run(run func(ctx context.Context, keyID string, secret string)) *MockAuthRepo_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthRepo_Verify_Call) Return(_a0 bool, _a1 error) *MockAuthRepo_Verify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthRepo_Verify_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockAuthRepo_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthRepo creates a new instance of MockAuthRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthRepo {
	mock := &MockAuthRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
