// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package core

import (
	context "context"

	conn "github.com/ksysoev/make-it-public/pkg/core/conn"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockControlConn is an autogenerated mock type for the ControlConn type
type MockControlConn struct {
	mock.Mock
}

type MockControlConn_Expecter struct {
	mock *mock.Mock
}

func (_m *MockControlConn) EXPECT() *MockControlConn_Expecter {
	return &MockControlConn_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockControlConn) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockControlConn_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockControlConn_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockControlConn_Expecter) Close() *MockControlConn_Close_Call {
	return &MockControlConn_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockControlConn_Close_Call) Run(run func()) *MockControlConn_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControlConn_Close_Call) Return(_a0 error) *MockControlConn_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockControlConn_Close_Call) RunAndReturn(run func() error) *MockControlConn_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function with no fields
func (_m *MockControlConn) Context() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// MockControlConn_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockControlConn_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockControlConn_Expecter) Context() *MockControlConn_Context_Call {
	return &MockControlConn_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockControlConn_Context_Call) Run(run func()) *MockControlConn_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControlConn_Context_Call) Return(_a0 context.Context) *MockControlConn_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockControlConn_Context_Call) RunAndReturn(run func() context.Context) *MockControlConn_Context_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with no fields
func (_m *MockControlConn) ID() uuid.UUID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	return r0
}

// MockControlConn_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockControlConn_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockControlConn_Expecter) ID() *MockControlConn_ID_Call {
	return &MockControlConn_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockControlConn_ID_Call) Run(run func()) *MockControlConn_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControlConn_ID_Call) Return(_a0 uuid.UUID) *MockControlConn_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockControlConn_ID_Call) RunAndReturn(run func() uuid.UUID) *MockControlConn_ID_Call {
	_c.Call.Return(run)
	return _c
}

// RequestConnection provides a mock function with no fields
func (_m *MockControlConn) RequestConnection() (conn.Request, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequestConnection")
	}

	var r0 conn.Request
	var r1 error
	if rf, ok := ret.Get(0).(func() (conn.Request, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() conn.Request); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(conn.Request)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockControlConn_RequestConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestConnection'
type MockControlConn_RequestConnection_Call struct {
	*mock.Call
}

// RequestConnection is a helper method to define mock.On call
func (_e *MockControlConn_Expecter) RequestConnection() *MockControlConn_RequestConnection_Call {
	return &MockControlConn_RequestConnection_Call{Call: _e.mock.On("RequestConnection")}
}

func (_c *MockControlConn_RequestConnection_Call) Run(run func()) *MockControlConn_RequestConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControlConn_RequestConnection_Call) Return(_a0 conn.Request, _a1 error) *MockControlConn_RequestConnection_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockControlConn_RequestConnection_Call) RunAndReturn(run func() (conn.Request, error)) *MockControlConn_RequestConnection_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockControlConn creates a new instance of MockControlConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockControlConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockControlConn {
	mock := &MockControlConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
