// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package core

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTCPEndpointAllocator is an autogenerated mock type for the TCPEndpointAllocator type
type MockTCPEndpointAllocator struct {
	mock.Mock
}

type MockTCPEndpointAllocator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTCPEndpointAllocator) EXPECT() *MockTCPEndpointAllocator_Expecter {
	return &MockTCPEndpointAllocator_Expecter{mock: &_m.Mock}
}

// Allocate provides a mock function with given fields: ctx, keyID
func (_m *MockTCPEndpointAllocator) Allocate(ctx context.Context, keyID string) (string, error) {
	ret := _m.Called(ctx, keyID)

	if len(ret) == 0 {
		panic("no return value specified for Allocate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, keyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, keyID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, keyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTCPEndpointAllocator_Allocate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Allocate'
type MockTCPEndpointAllocator_Allocate_Call struct {
	*mock.Call
}

// Allocate is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID string
func (_e *MockTCPEndpointAllocator_Expecter) Allocate(ctx interface{}, keyID interface{}) *MockTCPEndpointAllocator_Allocate_Call {
	return &MockTCPEndpointAllocator_Allocate_Call{Call: _e.mock.On("Allocate", ctx, keyID)}
}

func (_c *MockTCPEndpointAllocator_Allocate_Call) Run(run func(ctx context.Context, keyID string)) *MockTCPEndpointAllocator_Allocate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTCPEndpointAllocator_Allocate_Call) Return(_a0 string, _a1 error) *MockTCPEndpointAllocator_Allocate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTCPEndpointAllocator_Allocate_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockTCPEndpointAllocator_Allocate_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function with given fields: keyID
func (_m *MockTCPEndpointAllocator) Release(keyID string) {
	_m.Called(keyID)
}

// MockTCPEndpointAllocator_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type MockTCPEndpointAllocator_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - keyID string
func (_e *MockTCPEndpointAllocator_Expecter) Release(keyID interface{}) *MockTCPEndpointAllocator_Release_Call {
	return &MockTCPEndpointAllocator_Release_Call{Call: _e.mock.On("Release", keyID)}
}

func (_c *MockTCPEndpointAllocator_Release_Call) Run(run func(keyID string)) *MockTCPEndpointAllocator_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTCPEndpointAllocator_Release_Call) Return() *MockTCPEndpointAllocator_Release_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTCPEndpointAllocator_Release_Call) RunAndReturn(run func(string)) *MockTCPEndpointAllocator_Release_Call {
	_c.Run(run)
	return _c
}

// NewMockTCPEndpointAllocator creates a new instance of MockTCPEndpointAllocator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTCPEndpointAllocator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTCPEndpointAllocator {
	mock := &MockTCPEndpointAllocator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
