name: Deploy

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: deploy
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@2ead5e36573f08b82fbfce1504f1a4b05a647c6f
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSH_KEY}}
          port: ${{secrets.PORT}}
          envs: GITHUB_REF,GITHUB_SHA
          script: |
            cd make-it-public
            # Ensure we have a complete repository with all objects
            git fetch --prune --unshallow
            # Try to checkout the target reference
            if [ -n "$GITHUB_SHA" ]; then
              git checkout $GITHUB_SHA
            else
              BRANCH_NAME=${GITHUB_REF#refs/heads/}
              git checkout $BRANCH_NAME
            fi
            docker compose build
            docker stack deploy -c docker-compose.yml makeitpublic
