name: Deploy

permissions:
  contents: read

on:
#    push:
#        branches:
#        - main
#        tags:
#        - v*
#    pull_request:
#
    workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: deploy
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@2ead5e36573f08b82fbfce1504f1a4b05a647c6f
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSH_KEY}}
          port: ${{secrets.PORT}}
          envs: CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}
          script: |
            cd make-it-public
            git pull
            docker compose pull
            export CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN
            docker stack deploy -c docker-compose.yml makeitpublic
