name: Deploy

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: deploy
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@2ead5e36573f08b82fbfce1504f1a4b05a647c6f
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSH_KEY}}
          port: ${{secrets.PORT}}
          script: |
            git clone git@github.com:ksysoev/make-it-public.git
            echo 'Deployment to digital ocean finished'